echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "I have added new this for branch_1"
echo "I have added this newly addedgit add"
echo "I have added this newly addedgit  to add"
